CREATE TABLE `day02` (
	`num` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(8) NULL DEFAULT NULL,
	`sub` VARCHAR(20) NULL DEFAULT '제목없음',
	`content` TEXT NULL,
	`nalja` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`num`)
)